[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info


#################################################
# INPUT
#################################################

[INPUT]
    Name tail
    Path /var/log/*.log
    Tag local.logs
    Refresh_Interval 5
    Read_from_Head true


#################################################
# OUTPUT TO KAFKA
#################################################

[OUTPUT]
    Name kafka
    Match *
    Brokers kafka:29092
    Topics raw-logs

    Format json
    Timestamp_Key timestamp
    Retry_Limit false